name: app

services:
  backend:
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: env/prod/Dockerfile
      ssh:
        - default
    environment:
      - ENVIRONMENT=prod
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - inet
    depends_on:
      - database

  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_prod
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inet

volumes:
  postgres_data:

networks:
  inet:
    driver: bridge